### ISSUE TITLE
[FEAT] EDA - Annotation Analysis Code 작성

### ISSUE THREAD

**Issue by uowol** [boostcampaitech6/level2-objectdetection-cv-02#10]
## Background
- COCO format의 annotation 파일을 분석하고 insight를 구한다.

## Todo
- [x] class 분포 시각화
- [x] bbox 분포 시각화
- [x] 통계치 산출 및 분석

## Issue
#4
